# Generated by Django 3.2.13 on 2022-06-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(max_length=50, upload_to=''),
        ),
    ]
